In [2]:
import pandas as pd
import plotly.express as px

In [95]:
layer_info = {
    "Sustrans National Cycle Network Route":{"group":"Map5",
                                            "group_field":"Desc_",
                                            "unit":"METERS",
                                            "unit_type":"Length"},
    "Sustrans_Regional Cycle Route":{"group":"Map5",
                     "group_field":"Descriptio",
                                            "unit":"METERS",
                                            "unit_type":"Length"},
    "Sustrans Reclassified Cycle Route":{"group":"Map5",
                     "group_field":"Desc_",
                                            "unit":"METERS",
                                            "unit_type":"Length"},
    "Public Rights of Way":{"group":"Map5",
                     "group_field":"LYR_NAME",
                                            "unit":"METERS",
                                            "unit_type":"Length"},
    "FC Forest Roads":{"group":"Map5",
                     "group_field":False,
                                            "unit":"METERS",
                                            "unit_type":"Area"},
    # "CRoW S16 Dedicated Land":{"group":"Map5",
    #                  "group_field":False,
    #                  "unit":"HECTARES"},
    # "CRoW_S15 Land All Types":{"group":"Map5",
    #                  "group_field":False,
    #                  "unit":"HECTARES"},
    # "Conclusive Registered Commons":{"group":"Map5",
    #                  "group_field":False,
    #                  "unit":"HECTARES"},
    # "Conclusive Open Country":{"group":"Map5",
    #                  "group_field":False,
    #                  "unit":"HECTARES"},
    #  "CRoW Access Land":{"group":"Map5",
    #                  "group_field":False,
    #                  "unit":"HECTARES"},
    # "OS Greenspace":{"group":"Map5",
    #                  "group_field":"function",
    #                  "unit":"HECTARES"},
    # "NE Country Parks":{"group":"Map5",
    #                  "group_field":False,
    #                  "unit":"HECTARES"},
    # "Agricultural Land Classification":{"group":"Map6",
    #                  "group_field":":ALC_GRADE",
    #                  "unit":"HECTARES"},
    # "Environmental Stewardship Scheme":{"group":"Map7",
    #                  "group_field":"SCHEME",
    #                  "unit":"HECTARES"},
    # "Organic Farming Scheme":{"group":"Map7",
    #                  "group_field":"SCHEME",
    #                  "unit":"HECTARES"},
    "Countryside Stewardship Scheme":{"group":"Map7",
                     "group_field":"cs_type",
                     "unit":"HECTARES",
                                            "unit_type":"Area"},
    "RPA Landcovers":{"group":"Map8",
                     "group_field":"COVER_TYPE",
                     "unit":"HECTARES",
                                            "unit_type":"Area"},
    # "RPA Land Parcels":{"group":"Map9",
    #                  "group_field":"FarmID",
    #                  "unit":"HECTARES"},
    # "WSBRC Wiltshire eNGO Sites":{"group":"Map10",
    #                  "group_field":False},
    # "WSBRC Wiltshire eNGO Sites":{"group":"Map10",
    #                  "group_field":False},
    
}

In [6]:
location = "O:/LocalAuthorities/Neighbourhood_Plans/Research/Summary stats/Python/map-outputs"
location_data = "O:/LocalAuthorities/Neighbourhood_Plans/Research/NeigbourhoodPlansPython/"

In [96]:


df_all = pd.DataFrame({'NAME': [], 'value': [],'groupColumnValue': [],'groupColumnName': [],'mapGroup': [],'mapName': []})

for layer in layer_info.keys():
    layer_name = layer.replace(" ","_")
    if layer_info[layer]['group_field']:
      df_table = pd.read_csv(f"{location_data}/{layer_info[layer]['group']}_{layer_name}_table.csv")
      df_layer = pd.read_csv(f"{location_data}/{layer_info[layer]['group']}_{layer_name}.csv")
      df_table.rename(columns = {f"{layer_info[layer]['group_field']}":"groupColumnValue"}, inplace=True)
      df_table.rename(columns = {f"sum_{layer_info[layer]['unit_type']}_{layer_info[layer]['unit']}":"value"}, inplace=True)
      df_layer_all = df_layer[["NAME", "Join_ID"]].merge(df_table, on="Join_ID")
      # df_layer_all = df_layer_all[['NAME', f"sum_Area_{layer_info[layer]['unit']}",  
      #    "groupColumnValue"]]
      df_layer_all["mapGroup"] = f"{layer_info[layer]['group']}"
      df_layer_all["mapName"] = f"{layer_name}"
      df_layer_all["groupColumnName"] = layer_info[layer]['group_field']
      df_layer_all["unitName"] = layer_info[layer]['unit']
      print(df_layer_all.columns)
      df_layer_all = df_layer_all[['NAME', "value","mapGroup","mapName","groupColumnName","groupColumnValue","unitName"]]
      df_all = pd.concat([df_all,df_layer_all ])
    else:
      df_layer = pd.read_csv(f"{location_data}/{layer_info[layer]['group']}_{layer_name}.csv")
      df_table.rename(columns = {f"sum_{layer_info[layer]['unit_type']}_{layer_info[layer]['unit']}":"value"}, inplace=True)
      df_layer_all = df_layer_all[['NAME', "value"]]
      df_layer_all["mapGroup"] = f"{layer_info[layer]['group']}"
      df_layer_all["mapName"] = f"{layer_name}"
      df_layer_all["groupColumnName"] = "ALL"
      df_layer_all["groupColumnValue"] = "ALL"
      df_layer_all["unitName"] = layer_info[layer]['unit']
      df_layer_all = df_layer_all[['NAME', "value","mapGroup","mapName","groupColumnName","groupColumnValue","unitName"]]
      df_all = pd.concat([df_all,df_layer_all ])

Index(['NAME', 'Join_ID', 'groupColumnValue', 'value', 'Polyline_Count',
       'PercentLength', 'mapGroup', 'mapName', 'groupColumnName', 'unitName'],
      dtype='object')
Index(['NAME', 'Join_ID', 'groupColumnValue', 'value', 'Polyline_Count',
       'PercentLength', 'mapGroup', 'mapName', 'groupColumnName', 'unitName'],
      dtype='object')
Index(['NAME', 'Join_ID', 'groupColumnValue', 'value', 'Polyline_Count',
       'PercentLength', 'mapGroup', 'mapName', 'groupColumnName', 'unitName'],
      dtype='object')
Index(['NAME', 'Join_ID', 'groupColumnValue', 'value', 'Polyline_Count',
       'PercentLength', 'mapGroup', 'mapName', 'groupColumnName', 'unitName'],
      dtype='object')
Index(['NAME', 'Join_ID', 'groupColumnValue', 'value', 'Polygon_Count',
       'PercentArea', 'mapGroup', 'mapName', 'groupColumnName', 'unitName'],
      dtype='object')
Index(['NAME', 'Join_ID', 'groupColumnValue', 'value', 'Polygon_Count',
       'PercentArea', 'mapGroup', 'mapName', 'groupColumnName', 'unitName'],
      dtype='object')

In [97]:
df_all.to_csv('test.csv')

In [87]:
df_colerne = df_all[df_all.NAME=="Colerne"]

In [89]:
df_colerne

,NAME,value,groupColumnValue,groupColumnName,mapGroup,mapName,unitName
546,Colerne,6756.262426,Bridleway,LYR_NAME,Map5,Public_Rights_of_Way,METERS
547,Colerne,91.423655,Byway,LYR_NAME,Map5,Public_Rights_of_Way,METERS
548,Colerne,23753.524032,Footpath,LYR_NAME,Map5,Public_Rights_of_Way,METERS
410,Colerne,0.544437,CS CAPITAL GRANTS,cs_type,Map7,Countryside_Stewardship_Scheme,HECTARES
411,Colerne,4.963436,Higher Tier,cs_type,Map7,Countryside_Stewardship_Scheme,HECTARES
412,Colerne,493.422733,Mid Tier,cs_type,Map7,Countryside_Stewardship_Scheme,HECTARES
413,Colerne,126.059094,TREE HEALTH RESTORATION,cs_type,Map7,Countryside_Stewardship_Scheme,HECTARES
414,Colerne,151.439163,WOODLAND MANAGEMENT PLAN,cs_type,Map7,Countryside_Stewardship_Scheme,HECTARES
3049,Colerne,272.238736,Arable land,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3050,Colerne,0.023051,Drain/ditch/dyke,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3051,Colerne,1.006243,Farm building,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3052,Colerne,1.641816,Farmyards,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3053,Colerne,0.044663,Gallop,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3054,Colerne,1.403015,Hard standing,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3055,Colerne,1.294221,Metalled track,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3056,Colerne,11.485512,Natural woodland,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3057,Colerne,0.040069,Notional - scrub,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3058,Colerne,1.146903,Permanent crops,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3059,Colerne,712.165027,Permanent grassland,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3060,Colerne,0.434852,Pond,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3061,Colerne,0.011885,"Residential dwelling, house",COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3062,Colerne,0.598971,Residential gardens,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3063,Colerne,0.661546,Rivers and Streams type 2,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3064,Colerne,0.142083,Rivers and Streams type 3,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3065,Colerne,0.224822,Roads,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3066,Colerne,4.075842,Scrub - ungrazeable,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3067,Colerne,0.039831,Storage area,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3068,Colerne,0.008190,Structure,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3069,Colerne,4.224304,Track - natural surface,COVER_TYPE,Map8,RPA_Landcovers,HECTARES
3070,Colerne,245.973024,Woodland,COVER_TYPE,Map8,RPA_Landcovers,HECTARES

In [ ]:

df_table.rename(columns = {"sum_Area_HECTARES":"AreaHa_RPA_Landcovers"}, inplace=True)

In [ ]:
df_all = df_layer[["NAME", "sum_Area_HECTARES","Join_ID"]].merge(df_table, on="Join_ID")
df_all = df_all[['NAME', 'sum_Area_HECTARES', 'Join_ID', 'COVER_TYPE',
       'AreaHa_RPA_Landcovers']]

In [ ]:
layer_info['RPA Landcovers']

dict_keys(['RPA Landcovers'])

In [4]:
df_colerne = df_all[df_all.NAME == "Colerne"]

In [7]:
fig = px.bar(df_colerne, x = "MainHabs", y = "PercentArea")
fig.show()

In [9]:
df_all.columns

Index(['Join_ID', 'MainHabs', 'sum_AreaHa_x', 'sum_Area_SQUAREKILOMETERS_x',
       'Polygon_Count_x', 'PercentArea', 'NAME', 'AREA_CODE', 'DESCRIPTIO',
       'FILE_NAME', 'NUMBER', 'NUMBER0', 'POLYGON_ID', 'UNIT_ID', 'CODE',
       'HECTARES', 'AREA', 'TYPE_CODE', 'DESCRIPT0', 'TYPE_COD0', 'DESCRIPT1',
       'TO_Check', 'Shape_Length', 'Shape_Area', 'sum_AreaHa_y',
       'sum_Area_SQUAREKILOMETERS_y', 'Polygon_Count_y'],
      dtype='object')

In [14]:
df_all_reduced = df_all[["MainHabs", 'sum_AreaHa_x','PercentArea', 'NAME']]

In [26]:
df_all.columns

Index(['Join_ID', 'MainHabs', 'sum_AreaHa_x', 'sum_Area_SQUAREKILOMETERS_x',
       'Polygon_Count_x', 'PercentArea', 'NAME', 'AREA_CODE', 'DESCRIPTIO',
       'FILE_NAME', 'NUMBER', 'NUMBER0', 'POLYGON_ID', 'UNIT_ID', 'CODE',
       'HECTARES', 'AREA', 'TYPE_CODE', 'DESCRIPT0', 'TYPE_COD0', 'DESCRIPT1',
       'TO_Check', 'Shape_Length', 'Shape_Area', 'sum_AreaHa_y',
       'sum_Area_SQUAREKILOMETERS_y', 'Polygon_Count_y'],
      dtype='object')

In [62]:
df_wide = df_all.pivot(columns = "MainHabs",index = ["NAME",'sum_AreaHa_y'],values = [ 'sum_AreaHa_x'])

In [35]:
df_wide = df_wide.reset_index()

In [64]:
df_1 = df_wide.droplevel(1)

In [65]:
df_1.reset_index()

                    NAME                         sum_AreaHa_x  \
MainHabs                 Coastal and floodplain grazing marsh
0              Aldbourne                                  NaN
1              Alderbury                            80.282201
2           All Cannings                                  NaN
3              Allington                                  NaN
4                  Alton                                  NaN
..                   ...                                  ...
273               Worton                                  NaN
274            Wroughton                                  NaN
275                Wylye                            37.227931
276       Yatton Keynell                                  NaN
277                Zeals                                  NaN

                                                                  \
MainHabs Deciduous woodland Good quality semi improved grassland
0                112.806569                                  NaN
1                113.684266                                 6.48
2                  3.288095                                54.56
3                 44.909382                                  NaN
4                 22.162646                                  NaN
..                      ...                                  ...
273                2.306168                                  NaN
274               71.912270                                 5.98
275               48.608966                                17.02
276               37.037649                                  NaN
277               27.352881                                 5.10

                                                                   \
MainHabs Good quality semi improved grassland,Traditional orchard
0                                                       NaN
1                                                       NaN
2                                                       NaN
3                                                       NaN
4                                                       NaN
..                                                      ...
273                                                     NaN
274                                                     NaN
275                                                     NaN
276                                                     NaN
277                                                     NaN

                                                                  \
MainHabs Lowland calcareous grassland Lowland dry acid grassland
0                           49.080356                        NaN
1                            8.575225                        NaN
2                           95.254775                        NaN
3                          262.895237                        NaN
4                          101.926944                        NaN
..                                ...                        ...
273                               NaN                        NaN
274                         38.149100                        NaN
275                        109.867612                        NaN
276                         23.660000                        NaN
277                          5.390000                        NaN

                                                                    \
MainHabs Lowland dry acid grassland,Lowland heathland Lowland fens
0                                                 NaN          NaN
1                                                 NaN          NaN
2                                                 NaN          NaN
3                                                 NaN          NaN
4                                                 NaN          NaN
..                                                ...          ...
273                                               NaN          NaN
274                                               NaN          NaN
275                                               NaN          NaN
276                                               NaN          NaN
277                                               NaN          NaN

                                            \
MainHabs Lowland heathland Lowland meadows
0                      NaN        4.880000
1                      NaN        0.000620
2                      NaN       16.867401
3                      NaN             NaN
4                      NaN        6.281162
..                     ...             ...
273                    NaN             NaN
274                    NaN       10.020000
275                    NaN        4.190000
276                    NaN             NaN
277                    NaN             NaN

                                                                \
MainHabs No main habitat but additional habitats present Ponds
0                                              61.156071   NaN
1                                              11.243232   NaN
2                                              32.458788   NaN
3                                              13.752699   NaN
4                                               0.026145   NaN
..                                                   ...   ...
273                                             0.460000   NaN
274                                             6.194275  0.04
275                                             4.840000   NaN
276                                             6.557539   NaN
277                                             1.819999  0.06


MainHabs Purple moor grass and rush pastures Traditional orchard
0                                        NaN                0.18
1                                        NaN                 NaN
2                                        NaN                0.66
3                                        NaN                0.55
4                                        NaN                0.04
..                                       ...                 ...
273                                      NaN                 NaN
274                                      NaN                0.28
275                                      NaN                0.51
276                                      NaN                0.12
277                                      NaN                0.09

[278 rows x 15 columns]